islandora.settings:
  type: config_object
  label: Settings
  mapping:
    islandora_base_url:
      type: string
    islandora_namespace_restriction_enforced:
      type: boolean
    islandora_pids_allowed:
      type: string
    islandora_basic_collection_generate_uuid:
      type: boolean
    islandora_use_object_semaphores:
      type: boolean
    islandora_semaphore_period:
      type: integer
    islandora_render_context_ingeststep:
      type: boolean
    islandora_show_print_option:
      type: boolean
    islandora_repository_pid:
      type: string
    islandora_defer_derivatives_on_ingest:
      type: boolean
    islandora_ds_replace_exclude_enforced:
      type: string
    islandora_metadata_display:
      type: string
    islandora_render_drupal_breadcrumbs:
      type: boolean
    islandora_risearch_use_itql_when_necessary:
      type: boolean
    islandora_require_obj_upload:
      type: boolean
    islandora_breadcrumbs_backends:
      type: string
    viewers:
      type: sequence
